source("rbwa.R")

bwt <- bwa.open("test_files/chrM.fa")

for(s in c(
		"GCATGTGTAATCTTACTAAGAGCTAATAGAAAGGCTAGGACCAAACCTAT",
		"GCATGTGTAATCTTACTAAGCTAATAGAAAGGCTAGGACCAAACCTAT",
		"CTATCTACTTCAAATTCCTCCCTGTACGAAAGGACAAGAGAAATAAGGCCTCACAAAGCGCCTTCCCCCGTAAATGATATCATCTCAACTTAGTAT",
		"TACTAAACCC",
		"GCGAACCCAACTTCGATTCCCTCGCCGATCTCCGACGGAGCCGTGTGCAT"	
		))
	{
	print(paste("QUERY:",s));
	hits<-bwa.map(bwt,s)
	print(hits)
	}


bwa.close(bwt);


